# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joshz/repos/chesshacks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joshz/repos/chesshacks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshz/repos/chesshacks/CMakeFiles /Users/joshz/repos/chesshacks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshz/repos/chesshacks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c_helpers

# Build rule for target.
c_helpers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_helpers
.PHONY : c_helpers

# fast build rule for target.
c_helpers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/build
.PHONY : c_helpers/fast

#=============================================================================
# Target rules for targets named nanobind-static

# Build rule for target.
nanobind-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanobind-static
.PHONY : nanobind-static

# fast build rule for target.
nanobind-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/build
.PHONY : nanobind-static/fast

.venv/lib/python3.14/site-packages/nanobind/src/common.o: .venv/lib/python3.14/site-packages/nanobind/src/common.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/common.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/common.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/common.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/common.i: .venv/lib/python3.14/site-packages/nanobind/src/common.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/common.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/common.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/common.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/common.s: .venv/lib/python3.14/site-packages/nanobind/src/common.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/common.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/common.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/common.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/error.o: .venv/lib/python3.14/site-packages/nanobind/src/error.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/error.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/error.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/error.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/error.i: .venv/lib/python3.14/site-packages/nanobind/src/error.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/error.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/error.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/error.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/error.s: .venv/lib/python3.14/site-packages/nanobind/src/error.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/error.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/error.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/error.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/implicit.o: .venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/implicit.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/implicit.i: .venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/implicit.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/implicit.s: .venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/implicit.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/implicit.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_func.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_func.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_func.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_func.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_func.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_func.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_func.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/nb_type.o: .venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_type.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/nb_type.i: .venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_type.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/nb_type.s: .venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_type.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/nb_type.cpp.s

.venv/lib/python3.14/site-packages/nanobind/src/trampoline.o: .venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/trampoline.o

# target to build an object file
.venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.o
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.o

.venv/lib/python3.14/site-packages/nanobind/src/trampoline.i: .venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/trampoline.i

# target to preprocess a source file
.venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.i
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.i

.venv/lib/python3.14/site-packages/nanobind/src/trampoline.s: .venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/trampoline.s

# target to generate assembly for a file
.venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/.venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.s
.PHONY : .venv/lib/python3.14/site-packages/nanobind/src/trampoline.cpp.s

src/bindings.o: src/bindings.cpp.o
.PHONY : src/bindings.o

# target to build an object file
src/bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/bindings.cpp.o
.PHONY : src/bindings.cpp.o

src/bindings.i: src/bindings.cpp.i
.PHONY : src/bindings.i

# target to preprocess a source file
src/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/bindings.cpp.i
.PHONY : src/bindings.cpp.i

src/bindings.s: src/bindings.cpp.s
.PHONY : src/bindings.s

# target to generate assembly for a file
src/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/bindings.cpp.s
.PHONY : src/bindings.cpp.s

src/chess_board.o: src/chess_board.cpp.o
.PHONY : src/chess_board.o

# target to build an object file
src/chess_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/chess_board.cpp.o
.PHONY : src/chess_board.cpp.o

src/chess_board.i: src/chess_board.cpp.i
.PHONY : src/chess_board.i

# target to preprocess a source file
src/chess_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/chess_board.cpp.i
.PHONY : src/chess_board.cpp.i

src/chess_board.s: src/chess_board.cpp.s
.PHONY : src/chess_board.s

# target to generate assembly for a file
src/chess_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/chess_board.cpp.s
.PHONY : src/chess_board.cpp.s

src/cuda/cuda_utils.o: src/cuda/cuda_utils.cpp.o
.PHONY : src/cuda/cuda_utils.o

# target to build an object file
src/cuda/cuda_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/cuda/cuda_utils.cpp.o
.PHONY : src/cuda/cuda_utils.cpp.o

src/cuda/cuda_utils.i: src/cuda/cuda_utils.cpp.i
.PHONY : src/cuda/cuda_utils.i

# target to preprocess a source file
src/cuda/cuda_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/cuda/cuda_utils.cpp.i
.PHONY : src/cuda/cuda_utils.cpp.i

src/cuda/cuda_utils.s: src/cuda/cuda_utils.cpp.s
.PHONY : src/cuda/cuda_utils.s

# target to generate assembly for a file
src/cuda/cuda_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/cuda/cuda_utils.cpp.s
.PHONY : src/cuda/cuda_utils.cpp.s

src/evaluation.o: src/evaluation.cpp.o
.PHONY : src/evaluation.o

# target to build an object file
src/evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/evaluation.cpp.o
.PHONY : src/evaluation.cpp.o

src/evaluation.i: src/evaluation.cpp.i
.PHONY : src/evaluation.i

# target to preprocess a source file
src/evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/evaluation.cpp.i
.PHONY : src/evaluation.cpp.i

src/evaluation.s: src/evaluation.cpp.s
.PHONY : src/evaluation.s

# target to generate assembly for a file
src/evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/evaluation.cpp.s
.PHONY : src/evaluation.cpp.s

src/move_ordering.o: src/move_ordering.cpp.o
.PHONY : src/move_ordering.o

# target to build an object file
src/move_ordering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/move_ordering.cpp.o
.PHONY : src/move_ordering.cpp.o

src/move_ordering.i: src/move_ordering.cpp.i
.PHONY : src/move_ordering.i

# target to preprocess a source file
src/move_ordering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/move_ordering.cpp.i
.PHONY : src/move_ordering.cpp.i

src/move_ordering.s: src/move_ordering.cpp.s
.PHONY : src/move_ordering.s

# target to generate assembly for a file
src/move_ordering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/move_ordering.cpp.s
.PHONY : src/move_ordering.cpp.s

src/nnue_evaluator.o: src/nnue_evaluator.cpp.o
.PHONY : src/nnue_evaluator.o

# target to build an object file
src/nnue_evaluator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/nnue_evaluator.cpp.o
.PHONY : src/nnue_evaluator.cpp.o

src/nnue_evaluator.i: src/nnue_evaluator.cpp.i
.PHONY : src/nnue_evaluator.i

# target to preprocess a source file
src/nnue_evaluator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/nnue_evaluator.cpp.i
.PHONY : src/nnue_evaluator.cpp.i

src/nnue_evaluator.s: src/nnue_evaluator.cpp.s
.PHONY : src/nnue_evaluator.s

# target to generate assembly for a file
src/nnue_evaluator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/nnue_evaluator.cpp.s
.PHONY : src/nnue_evaluator.cpp.s

src/opening_book.o: src/opening_book.cpp.o
.PHONY : src/opening_book.o

# target to build an object file
src/opening_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/opening_book.cpp.o
.PHONY : src/opening_book.cpp.o

src/opening_book.i: src/opening_book.cpp.i
.PHONY : src/opening_book.i

# target to preprocess a source file
src/opening_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/opening_book.cpp.i
.PHONY : src/opening_book.cpp.i

src/opening_book.s: src/opening_book.cpp.s
.PHONY : src/opening_book.s

# target to generate assembly for a file
src/opening_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/opening_book.cpp.s
.PHONY : src/opening_book.cpp.s

src/search_and_utils.o: src/search_and_utils.cpp.o
.PHONY : src/search_and_utils.o

# target to build an object file
src/search_and_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/search_and_utils.cpp.o
.PHONY : src/search_and_utils.cpp.o

src/search_and_utils.i: src/search_and_utils.cpp.i
.PHONY : src/search_and_utils.i

# target to preprocess a source file
src/search_and_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/search_and_utils.cpp.i
.PHONY : src/search_and_utils.cpp.i

src/search_and_utils.s: src/search_and_utils.cpp.s
.PHONY : src/search_and_utils.s

# target to generate assembly for a file
src/search_and_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/search_and_utils.cpp.s
.PHONY : src/search_and_utils.cpp.s

src/transposition_table.o: src/transposition_table.cpp.o
.PHONY : src/transposition_table.o

# target to build an object file
src/transposition_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/transposition_table.cpp.o
.PHONY : src/transposition_table.cpp.o

src/transposition_table.i: src/transposition_table.cpp.i
.PHONY : src/transposition_table.i

# target to preprocess a source file
src/transposition_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/transposition_table.cpp.i
.PHONY : src/transposition_table.cpp.i

src/transposition_table.s: src/transposition_table.cpp.s
.PHONY : src/transposition_table.s

# target to generate assembly for a file
src/transposition_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_helpers.dir/build.make CMakeFiles/c_helpers.dir/src/transposition_table.cpp.s
.PHONY : src/transposition_table.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... c_helpers"
	@echo "... nanobind-static"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/common.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/common.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/common.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/error.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/error.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/error.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/implicit.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/implicit.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/implicit.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_enum.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_ft.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_func.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_func.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_func.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_internals.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_ndarray.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_static_property.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_type.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_type.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/nb_type.s"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/trampoline.o"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/trampoline.i"
	@echo "... .venv/lib/python3.14/site-packages/nanobind/src/trampoline.s"
	@echo "... src/bindings.o"
	@echo "... src/bindings.i"
	@echo "... src/bindings.s"
	@echo "... src/chess_board.o"
	@echo "... src/chess_board.i"
	@echo "... src/chess_board.s"
	@echo "... src/cuda/cuda_utils.o"
	@echo "... src/cuda/cuda_utils.i"
	@echo "... src/cuda/cuda_utils.s"
	@echo "... src/evaluation.o"
	@echo "... src/evaluation.i"
	@echo "... src/evaluation.s"
	@echo "... src/move_ordering.o"
	@echo "... src/move_ordering.i"
	@echo "... src/move_ordering.s"
	@echo "... src/nnue_evaluator.o"
	@echo "... src/nnue_evaluator.i"
	@echo "... src/nnue_evaluator.s"
	@echo "... src/opening_book.o"
	@echo "... src/opening_book.i"
	@echo "... src/opening_book.s"
	@echo "... src/search_and_utils.o"
	@echo "... src/search_and_utils.i"
	@echo "... src/search_and_utils.s"
	@echo "... src/transposition_table.o"
	@echo "... src/transposition_table.i"
	@echo "... src/transposition_table.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

